
cc_binary(
    name="hello_world",
    srcs=[
        "*.cpp",
    ],
    deps=[
        "#pthread",
        "cpputil/json:1.0.0@//cpputil/json:json",
        "cpp3rdlib/boost:1.56.0@//cpp3rdlib//boost:boost",
        "cpp3rdlib/boost:1.56.0@//cpp3rdlib//rapidjson:rapidjson",
    ]
)