cc_library(
    name="boost",
    export_incs=["include"],
    prebuilt=True,
    onlyinc=True,
)

cc_library(
    name="boost_atomic",
    export_incs=["include"],
    build_dynamic=True,
    prebuilt=True,
)

cc_library(
    name="boost_chrono",
    deps=[":boost_system"],
    export_incs=["include"],
    build_dynamic=True,
    prebuilt=True,
)

cc_library(
    name="boost_container",
    export_incs=["include"],
    build_dynamic=True,
    prebuilt=True,
)

cc_library(
    name="boost_context",
    export_incs=["include"],
    build_dynamic=True,
    prebuilt=True,
)

cc_library(
    name="boost_coroutine",
    deps=[":boost_thread", ":boost_context", ":boost_chrono", ":boost_system"],
    export_incs=["include"],
    build_dynamic=True,
    prebuilt=True,
)

cc_library(
    name="boost_date_time",
    export_incs=["include"],
    build_dynamic=True,
    prebuilt=True,
)

cc_library(
    name="boost_exception",
    export_incs=["include"],
    build_dynamic=True,
    prebuilt=True,
)

cc_library(
    name="boost_filesystem",
    deps=[":boost_system"],
    export_incs=["include"],
    build_dynamic=True,
    prebuilt=True,
)

cc_library(
    name="boost_graph",
    deps=[":boost_regex"],
    export_incs=["include"],
    build_dynamic=True,
    prebuilt=True,
)

cc_library(
    name="boost_iostreams",
    export_incs=["include"],
    build_dynamic=True,
    prebuilt=True,
)

cc_library(
    name="boost_locale",
    deps=[":boost_thread", ":boost_chrono", ":boost_system"],
    export_incs=["include"],
    build_dynamic=True,
    prebuilt=True,
)

cc_library(
    name="boost_log",
    deps=[":boost_regex", ":boost_filesystem", ":boost_date_time", ":boost_thread", ":boost_chrono", ":boost_system"],
    export_incs=["include"],
    build_dynamic=True,
    prebuilt=True,
)

cc_library(
    name="boost_log_setup",
    deps=[":boost_log"],
    export_incs=["include"],
    build_dynamic=True,
    prebuilt=True,
)

cc_library(
    name="boost_math_c99",
    export_incs=["include"],
    build_dynamic=True,
    prebuilt=True,
)

cc_library(
    name="boost_math_c99f",
    export_incs=["include"],
    build_dynamic=True,
    prebuilt=True,
)

cc_library(
    name="boost_math_c99l",
    export_incs=["include"],
    build_dynamic=True,
    prebuilt=True,
)

cc_library(
    name="boost_math_tr1",
    export_incs=["include"],
    build_dynamic=True,
    prebuilt=True,
)

cc_library(
    name="boost_math_tr1f",
    export_incs=["include"],
    build_dynamic=True,
    prebuilt=True,
)

cc_library(
    name="boost_math_tr1l",
    export_incs=["include"],
    build_dynamic=True,
    prebuilt=True,
)

cc_library(
    name="boost_prg_exec_monitor",
    export_incs=["include"],
    build_dynamic=True,
    prebuilt=True,
)

cc_library(
    name="boost_program_options",
    export_incs=["include"],
    build_dynamic=True,
    prebuilt=True,
)

cc_library(
    name="boost_python",
    export_incs=["include"],
    build_dynamic=True,
    prebuilt=True,
)

cc_library(
    name="boost_random",
    deps=[":boost_system"],
    export_incs=["include"],
    build_dynamic=True,
    prebuilt=True,
)

cc_library(
    name="boost_regex",
    export_incs=["include"],
    build_dynamic=True,
    prebuilt=True,
)

cc_library(
    name="boost_serialization",
    export_incs=["include"],
    build_dynamic=True,
    prebuilt=True,
)

cc_library(
    name="boost_signals",
    export_incs=["include"],
    build_dynamic=True,
    prebuilt=True,
)

cc_library(
    name="boost_system",
    export_incs=["include"],
    build_dynamic=True,
    prebuilt=True,
)

cc_library(
    name="boost_test_exec_monitor",
    export_incs=["include"],
    build_dynamic=True,
    prebuilt=True,
)

cc_library(
    name="boost_thread",
    deps=[":boost_system"],
    export_incs=["include"],
    build_dynamic=True,
    prebuilt=True,
)

cc_library(
    name="boost_timer",
    deps=[":boost_chrono", ":boost_system"],
    export_incs=["include"],
    build_dynamic=True,
    prebuilt=True,
)

cc_library(
    name="boost_unit_test_framework",
    export_incs=["include"],
    build_dynamic=True,
    prebuilt=True,
)

cc_library(
    name="boost_wave",
    deps=[":boost_chrono", ":boost_date_time", ":boost_thread", ":boost_filesystem", ":boost_system"],
    export_incs=["include"],
    build_dynamic=True,
    prebuilt=True,
)

cc_library(
    name="boost_wserialization",
    deps=[":boost_serialization"],
    export_incs=["include"],
    build_dynamic=True,
    prebuilt=True,
)

